---
title: "Syllabus"
book_filename: psyc173
output:
  word_document:
    toc: true
  html_document:
    toc: true
    theme: united
  pdf_document:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<p align="center">**San Jos&eacute; State University**</p>

<p align="center">**Department of Psychology**</p>

<p align="center">**PSYC 173: Human Factors**</p>

<p align="center">**Section 1, Fall 2024**</p>

<p align="center">Last updated: `r format(Sys.time(), '%B %d, %Y')`</p>

<p align="center">**This version may be out of date. Find the [latest version here](https://vectrlab.github.io/human-factors-syllabus/index.html)**</p>

# Instructor Contact Information
Instructor:	      David Schuster, Ph.D.

Office Location:	DMH 321

Telephone:	      408-924-5659

Email:	          david.schuster@sjsu.edu

Office Hours:	    Tuesdays and Thursdays 2:00pm-2:50pm in person and on [Zoom meeting](https://sjsu.zoom.us/j/86362443375?pwd=ZCsvMzdFWldBUTV3WGZ4a1lwaUtGdz09); also available by appointment

# Course Information
Classroom:	      DMH 356

Class Days/Time:	Tues. & Thurs., 3:00pm - 4:15pm

Prerequisites:	  PSYC 001 or equivalent

# Welcome!

My name is David Schuster, and you are welcome to call me 'Dave,' 'David,' or 'Dr. Schuster.' My preferred pronouns are he/him/his. I have been teaching college since 2008 and a professor at SJSU since 2013. I earned my Ph.D. in psychology from the University of Central Florida. I am looking forward to being your instructor as we explore how the interdisciplinary field of human factors can increase the safety and effectiveness of human-machine systems.

I am here to help you, so please take advantage of opportunities to meet with me during drop-in office hours and by appointment. In these meetings, you can ask me questions, further discuss any part of the course, talk about your plans after graduation, and connect to other resources on campus.

# Course Description
How can technology make our lives safer, more efficient, and more enjoyable? To answer this question, this course will introduce you to human factors, a field focused on understanding interactions among people, technologies, and other elements of a human-machine system. Human factors professionals improve human-machine systems by considering the capabilities, characteristics, and limitations of people.

The catalog description of this course is: Human psychology and physiological characteristics and methods for taking these into account in designs and development of human-machine systems. Current human factor engineering efforts in lab, design process and operational environment.

## Course Format

This is an asynchronous online course. That means that you will complete each week's material at your own pace.


# Learning Outcomes {#learningoutcomes}

## Course Learning Outcomes {#clos}

The major goal of this course is to show students how applied psychological research informs practice in domains of human-technology interaction.

Upon successful completion of this course, students will be able to:

-	CLO1 - Describe human factors, appropriately use its fundamental terminology, and describe its importance in the effectiveness of human-machine systems.

-	CLO2 - Apply research, principles, and methods of human factors to human-machine system design, system evaluation, and training.

-	CLO3 - Describe how human capabilities and limitations interact with design to affect human-machine system performance.

The learning outcomes will be assessed via assignments and the final project. 

## Program Learning Outcomes {#plos}
Upon successful completion of the requirements for a major in psychology, students will be able to:

-	PLO1 – Knowledge Base of Psychology – identify, describe, and communicate the major concepts, theoretical perspectives, empirical findings, and historical trends in psychology

-	PLO2 – Research Methods in Psychology – design, implement, and communicate basic research methods in psychology, including research design, data analysis, and interpretations

-	PLO3 – Critical Thinking Skills in Psychology – use critical and creative thinking, skeptical inquiry, and a scientific approach to address issues related to behavior and mental processes

-	PLO4 – Application of Psychology – apply psychological principles to individual, interpersonal, group, and societal issues

-	PLO5 – Values in Psychology – value empirical evidence, tolerate ambiguity, act ethically, and recognize their role and responsibility as a member of society

Each assignment in this course maps onto one or more of these PLOs, with full coverage over all assignments in the course. PLOs 1-3 are emphasized in the first weeks of the course, and PLOs 2-5 are emphasized in the subsequent weeks of the course.

# Required Materials {#requiredmaterials}

## Canvas and E-Mail

All graded assignments will be accepted in electronic form using the Canvas learning management system assignments page (Canvas is available at https://sjsu.instructure.com/). Communication regarding the course will be posted to Canvas or sent via the e-mail address linked to your MySJSU account. It is your responsibility to make sure you are enrolled in Canvas and receiving my emails.

## Required Texts/Readings
Lee, J. D., Wickens, C. D., Liu, Y., & Boyle, L. N. (2017). _Designing for people: An introduction to human factors engineering (3rd ed.)_. Charleston, SC: CreateSpace. ISBN: 9781539808008

You need the textbook all semester. In addition to using it for readings, we will use the textbook as reference material (e.g., tables of anthropometry data). Additional readings and videos will be made available on Canvas.

As of this writing, a scanned version of the first chapter is available on the [author's ResearchGate page](https://www.researchgate.net/publication/319402797_Designing_for_People_An_introduction_to_human_factors_engineering).

The author has also [posted](https://designing4people.com/index.php/2019/07/30/an-e-textbook-designing-for-people-an-introduction-to-human-factors-engineering-a-good-thing/) that Amazon is now offering an **electronic version to purchase for $15**. This edition seems to be a scanned PDF version, so it may or may not be suitable for your purposes.

## Computer

A laptop or tablet computer with Internet access will be necessary to participate in class activities and for your use outside of class. In lieu of a computer or tablet, paper notes along with a smartphone may be used, but that combination is unlikely to provide a good experience. You will need a keyboard. If you do not have a laptop or tablet computer available for this course, please meet with me to discuss free options for computer resources. I will work with you to find acceptable free computing resources.

You may choose to meet with me in person or via <a href="https://sjsu.zoom.us">Zoom</a>. A webcam and microphone are recommended but not required.

This course may require occasional use of software such as Google Docs and Sheets. I will provide instruction in the use of the software; you do not need to start the course with this knowledge. You do *not* need to purchase licenses for any software.

In case you need them, these software packages are available to you at no cost:

- [RStudio](https://www.rstudio.com)

- [R](https://cran.r-project.org)

- [SPSS](https://www.sjsu.edu/it/services/collaboration/software/instructions.php)

- [G*Power](https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower)

- [Adobe Creative Cloud](https://www.sjsu.edu/ecampus/software-tools/teaching-tools/video-creative/adobe/students.php)

- [Microsoft Office](https://www.office.com/getoffice365)

- [Google Drive](https://sjsu.drive.google.com)

# Grading Policy

## Determination of Grades

Grades will be available to you on Canvas throughout the semester. Grades are assigned based on your final point total out of 1000 points for the course:

--------------------------------------
Grade                 Points
--------------------- ----------------
A plus	              > 965 points

A	                    916 to 965 points

A minus	              896 to 915 points

B plus                866 to 895 points

B	                    816 to 865 points

B minus	              796 to 815 points

C plus	              766 to 795 points

C	                    716 to 765 points

C minus	              696 to 715 points

D plus	              666 to 695 points

D	                    616 to 665 points

D minus               595 to 615 points

F	                    < 595 points
--------------------------------------

## Rounding is Included in the Grading Scale

The point totals reflect rounding up to the nearest percentage. For example, an A- would normally require 900 points (or 90% of 1000 points). With rounding, it only requires 896 points (or 89.6% of 1000 points). Because rounding is built into the grading scale, your grade will be based on your final point total, rounded to the nearest whole point (so, 895.6 points is an A-, but 895.4 points is a B+). To be fair to everyone in the class, these are firm cutoffs.

# Course Requirements and Assignments {#assignments}

## Activity Assignments (48% of grade = 480 points)
Thirteen activity assignments will be worth 40 points each, but the lowest one will be dropped. Each assignment will be graded according to the rubric posted to Canvas. The activities are designed to give you hands-on practice with the techniques and ideas discussed in the lecture and readings. Part of every class meeting most weeks will be dedicated to collaborative work on the activity and will require some preparation before class, attending and participating in the activity session, and completing and submitting of the assignment after class. Activities will be assigned most weeks and will typically be due immediately at the start of class on the following Tuesday. You are encouraged to work collaboratively, but everyone must do their own work unless otherwise specified; copying is not acceptable. **You may not copy content written by other students or AI or chatbots (e.g., ChatGPT) to write your response to reflection questions, although you may use these tools to facilitate your learning.**. This is the difference between discussing and asking questions about your activity assignment, which is acceptable, and asking someone (or AI) to write your assignment for you, which is not acceptable and will be handled as academic dishonesty. That said, I will always encourage you to start with me for your questions, as AI tools are still emerging and can be unreliable. I may ask to meet with you to discuss your submitted assignments before assigning the grade. Maps to CLO1-3.

## Reflection Assignments (16.8% of grade = 168 points)
Thirteen reflection assignments are worth 14 points each, but the lowest one will be dropped. The purpose of the reflection assignments are to help you think actively about the lecture and textbook content and connect it to your own experience. Part of every class meeting most weeks will be dedicated to collaborative work on the reflection assignment, and you must be present in class to complete it. This is graded for completion; it is okay to not have the right answer, but it does need to reflect your thinking about the material. **Reflection questions must be written entirely using your own words, and you may not use AI or chatbots (e.g., ChatGPT) to write your response to reflection questions**.  This is because the goal of this assignment is for you to think about the material as you write. I may ask to meet with you to discuss your submitted assignments before assigning the grade. Maps onto CLOs 1-3.

## Project Milestone Assignments (15% of grade = 150 points)
You will be asked to prepare a project on a topic of your interest. The points for preparing the project are divided into two milestone assignments, each worth 75 points. Each project milestone assignment will be scored according to the rubric on Canvas. Maps to CLO1-3.

## Final Project (20% of grade = 202 points)
The final project follows directly from the milestone assignments and is worth 200 points. More details about the project, including a rubric for grading, will be posted to Canvas during the semester. If events outside your control impact completion of this assignment, you should meet with me to discuss options for a course incomplete. Maps to CLO1-3.


## Late Assignments and Make-Ups {#makeup}
Assignments are due as indicated on Canvas, and the deadlines are strict. Because of this, I encourage you to avoid submitting assignments in the last two hours before the due date whenever possible. Late activity assignments and project milestone assignments will be accepted with a 20% penalty per day. That is, an assignment submitted between 0 and 23 hours past the deadline will be accepted with a 20% reduction included after grading. An assignment submitted 24 hours past the deadline will be accepted with a 40% reduction included after grading. Please allow extra time for me to grade late-submitted assignments. If your circumstances warrant an exception to the late assignment penalty, such as due to a health emergency, complete **[this form](https://docs.google.com/forms/d/e/1FAIpQLSepJUy_f3Y2WXoCHIAHd_5hUgq3KBK6nc8mkMCvP6_vfc41Cw/viewform?usp=sf_link)** to request an exception. **When you need an exception to the late assignment penalty, I need the request form completed as soon as you are able to complete it**. If you wait, I may not be able to grant your request.

Class activities that are scheduled, such as reflection assignments, in-class activities, and guest speakers, cannot be reasonably recreated. If you need a makeup assignment (e.g., you will miss the talk needed to complete an assignment, or even if you had life events and could not focus on the talk), please complete **[this form](https://docs.google.com/forms/d/e/1FAIpQLSepJUy_f3Y2WXoCHIAHd_5hUgq3KBK6nc8mkMCvP6_vfc41Cw/viewform?usp=sf_link)** as soon as you are aware of your need for a make-up and able to do so. If your circumstances warrant an exception, I will work with you to create an alternative assignment. Make-ups are intended for exceptional, unforeseen, and unavoidable circumstances. There is no need to pretend you attended an activity that you missed.

### No assignment submission after the last day of instruction
I can only accept assignments (except the final project) until 11:59pm on the last day of instruction for the semester. At that time, all unsubmitted and unsatisfactory/no credit assignments will receive zero points. Should an event prevent you from completing the course, contact me as soon as you are able to discuss our options for an incomplete. 

Because the final project occurs after the conclusion of the course, I cannot offer extensions on the final project. If events outside your control impact completion of this assignment, you should meet with me to discuss options for a course incomplete.


## Final examination or evaluation {#final}

Faculty members are required to have a culminating activity for their courses, which can include a final examination, a final research paper or project, a final creative work or performance, a final portfolio of work, or other appropriate assignment.

The culminating activity for this course will be the final project presentation.


# Classroom Environment {#environment}

We agree to:

-	**Mutual respect**, which means that we recognize and value that we bring different skills, experiences, and qualities to our course, and we act with regard for how our behavior affects others. As much as we can, we recognize and accommodate individual constraints that impact our work. Some ways we will show mutual respect include:
    + Affirming that ableism, classism, racism, sexism, transphobia, heterosexism, and xenophobia will not be acceptable in the physical and digital spaces that make up our course. 
  
    + Respecting our and others’ intellectual property. For students, this includes not sharing or posting copyrighted class materials. For me, this includes seeking permission before publicly sharing or posting your work (unless for an educational purpose, checking for or responding to academic dishonesty, or due to legal action). Your work may be sent to turnitin.com and/or examined using analytic tools to detect academic dishonesty. However, I will not allow turnitin.com to store your work in their repository.
  
    + We understand that we have multiple obligations and limited time. Our meetings will start promptly at times convenient for both of us.
  
    + We understand that we are all doing our best as we face our own challenges. I will expect that you put in reasonable effort on your assignments. You can expect patience and help whenever you struggle with course material. And, I am always available to meet with you should life events impact your progress in the course or success in your program.

- **Academic and professional integrity**, which means that the credibility of science and education depends on us acting ethically. Ethical violations by us or our collaborators can jeopardize our research and harm our reputation as researchers. We also know that we cannot act ethically if we do not understand what that means for researchers. Therefore, it is important that research ethics are part of your learning in this class. You can expect support and guidance when you navigate and speak up on challenging ethical situations. You can also expect no tolerance of ethical or academic integrity violations that negatively affect our class or community, including cheating and plagiarism. You can expect your instructor to follow all University policies and protocols regarding the handling of suspected academic dishonesty. Penalties can include failure of the course.

-	**Unlimited support** related to the class and your professional training and development. This means that there is no limit to the number of questions you may ask, e-mails you may send, or hours you can spend in meetings with me. You need never apologize for asking a question or seeking support. Time is limited but support is not; if the volume of student meetings were to become unmanageable, I will make adjustments to help all students more efficiently (for example, by answering a common question to the whole class). I am always happy to help you.

-	**Incorporation of issues of social justice**. It is my goal to help prepare you to tackle the major societal challenges we face, including COVID-19 and broader issues of equity and sustainability. Success against these challenges requires equitable participation by people of diverse backgrounds and experiences. To support this goal, this course will incorporate discussion of social justice when relevant to the course and support your evaluation of how our discipline has/can/will address social justice, as well as how it has contributed to social injustice. 

# University Policies {#policies}

Per [University Policy S16-9](http://www.sjsu.edu/senate/docs/S16-9.pdf),relevant university policy concerning all courses, such as student responsibilities, academic integrity, accommodations, dropping and adding, consent for recording of class, etc. and available student services (e.g. learning assistance, counseling, and other resources) are listed on [Syllabus Information web page](https://www.sjsu.edu/curriculum/courses/syllabus-info.php). Make sure to visit this page to review and be aware of these university policies and resources.

You must obtain the instructor’s permission to make any audio or video recordings in this class. Unless otherwise specified, course materials created by your instructor are copyrighted and cannot be redistributed.

Success in this course is based on the expectation that students will spend, for each unit of credit, a minimum of 45 hours over the length of the course (normally three hours per unit per week) for instruction, preparation/studying, or course related activities, including but not limited to internships, labs, and clinical practica. Other course structures will have equivalent workload expectations as described in the syllabus. 

# Library Liaison 
Our library liaison is Christa Bailey. Email: christa.bailey@sjsu.edu

# Additional Information
APA format is preferred. The writing requirement is described above.

# Course Schedule {#schedule}

The course schedule is tentative and very likely to change; modifications will be posted to this page.

**See Canvas for all due dates**

----------------------------------------------------------------------------------------------------------------------------------------------------------
Week Starting Date          Topics                                                                      Textbook    Assignments (see Canvas for due dates)
---- ---------------------- --------------------------------------------------------------------------  ----------- --------------------------------------
1	    Thu., Aug. 22         Introduction to human factors                                               Ch. 1             

2	    Tue., Aug. 27         Human factors methods                                                       Ch. 2       Reflection 1

      Thu., Aug. 29                                                                                                 Activity 1, cta
    
3	    Tue., Sep. 3          Human factors methods, continued       	                                    Ch. 3       Reflection 2

      Thu., Sep. 5                                                                                                  Activity 2, metrics
 
4	    Tue., Sep. 10         Human factors in driving and monitoring                                     Ch. 4       Reflection 3

      Thu., Sep. 12                                                                                                 Activity 3, waldo

5	    Tue., Sep. 17         Cognitive engineering                                                       Ch. 6       Reflection 4

                            **Last day to drop or add**
                            
      Thu., Sep. 19                                                                                                 Activity 4, cardsort

6	    Tue., Sep. 24         Automation: Artificial Intelligence                                         Ch. 11      Reflection 5

      Thu., Sep. 26                                                                                                 Activity 5, AI 
      
7	    Tue., Oct. 1          Automation: Robotics                                                                    Reflection 6

      Thu., Oct. 3                                                                                                  Activity 6, robots      
      
8	    Tue., Oct. 8          Decision making and macrocognition                                          Ch. 7       Reflection 7

      Thu., Oct. 10                                                                                                 Activity 7, MAUT

9	    Tue., Oct. 15         Human-computer interaction (HCI) and user experience (UX)                   Ch. 10      Reflection 8

      Thu., Oct. 17                                                                                                 Activity 8, prototype
      
10	  Tue., Oct. 22         Sociotechnical systems                                                      Ch. 18      Reflection 9

      Thu., Oct. 24                                                                                                 Activity 9, article

11	  Tue., Oct. 29         Applied research                                                                        Project milestone 1

      Thu., Oct. 31                                                                                                  
      
12	  Tue., Nov. 5          Physical ergonomics & anthropometry                                         Ch. 12      Reflection 10

      Thu., Nov. 7                                                                                                  Activity 10, physical
      
13	  Tue., Nov. 12         Displays and controls                                                       Ch. 8       Reflection 11

      Thu., Nov. 14                                                                                                 Activity 11, heuristic      
14	  Tue., Nov. 19         Stress, workload, and safety                                                Ch. 15      Reflection 12

      Thu., Nov. 21                                                                                                 Activity 12

15	  Tue., Nov. 26         Project workshop                  

      Wed. Nov. 27          Non-instructional day

      Thu. Nov. 28          **Thanksgiving holiday, campus closed**
      
      Fri. Nov. 29          Rescheduled holiday, campus closed

16	  Tue., Dec. 3          Training and job design                                                     Ch. 17      Project milestone 2 

      Thu., Dec. 5                                                                                                  Activity 13, train
      
                                                                                                                    Reflection 13

      Mon. Dec. 9           Last day of instruction, make-up assignment submission ends 11:59 pm                            
      
Final Wed., Dec. 11		      Project presentations due, 2:45 PM                                                      Final project
------------------------------------------------------------------------------------------------------------------------------------------




